version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: vfarm-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-vertical_farm}
      MYSQL_USER: ${MYSQL_USER:-vfarm}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-vfarm_pass}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$${MYSQL_USER} -p$${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: vfarm-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.11
    container_name: vfarm-app
    restart: unless-stopped
    environment:
      APP_ENV: development
      SECRET_KEY: dev_secret
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: vertical_farm
      MYSQL_USER: vfarm
      MYSQL_PASSWORD: vfarm_pass
      MQTT_BROKER_HOST: mosquitto
      MQTT_BROKER_PORT: 1883
      LOG_LEVEL: INFO
      WATCHFILES_FORCE_POLLING: "true"
    depends_on:
      mysql:
        condition: service_healthy
      mosquitto:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  mysql_data:
  mosquitto_data:
  mosquitto_log:
